#!/bin/bash

echo "
[user]
	name = nicholas
	email = nicholaspham2311@gmail.com
" > ~/.gitconfig

mkdir git ; cd ~/git/

git clone git@github.com:nicholaspham2311/dotfiles-termux.git
git clone git@github.com:nicholaspham2311/dotfiles.git
git clone git@github.com:nicholaspham2311/pomodoro.git
git clone git@github.com:nicholaspham2311/mywebsite.git
git clone git@github.com:nicholaspham2311/study.git
git clone git@github.com:nicholaspham2311/lazyscript.git

mkdir ~/.config/nvim/ 
cp ~/git/dotfiles/nvim/init.vim ~/.config/nvim/
cp ~/git/dotfiles/vim/.vimrc ~/
cp ~/git/dotfiles/ssh/config ~/.ssh/
cp ~/git/dotfiles/tmux/.tmux.conf ~/
cp ~/git/dotfiles/fish/config.fish ~/.config/fish/
cp ~/git/dotfiles/fish/fish_prompt.fish ~/.config/fish/functions
cp ~/git/dotfiles/git/.gitconfig ~/ 
cp ~/git/dotfiles/ranger/* ~/.config/ranger
cp ~/git/dotfiles/.selected_editor ~/

git clone https://github.com/sherlock-project/sherlock.git ~/tools/hacking/sherlock/
cd ~/tools/hacking/sherlock/ ; python3 -m pip install -r requirements.txt
